def update_user_profile(cursor, profile_data):
    cursor.execute(
        """UPDATE User_profile SET
        attractiveness = ?, relationship_type = ?, family_planning = ?, living_address = ?, apartment_style = ?, roommates = ?,
        working_hours = ?, other_commitments = ?, dating_availability = ?, height = ?, weight = ?, age = ?, gender = ?, eye_color = ?,
        eye_type = ?, hair_color = ?, hair_length = ?, hair_style = ?, nose = ?, facial_form = ?, cheekbones = ?, eyebrows = ?, dept = ?,
        assets = ?, income_this_year = ?, income_next_year = ?, income_over_next_year = ?, wealth_goals = ?, kids = ?, pets = ?, living = ?,
        wealth_splitting = ?, effort_splitting = ?, religion = ?, politics = ?, existing_family_structure = ?, retirement = ?, q1 = ?, q2 = ?,
        q3 = ?, q4 = ?, q5 = ?, q6 = ?, q7 = ?, q8 = ?, q9 = ?, q10 = ?
        WHERE unique_id = ?""",
        (
            profile_data["attractiveness"],
            profile_data["relationship_type"],
            profile_data["family_planning"],
            profile_data["living_address"],
            profile_data["apartment_style"],
            profile_data["roommates"],
            profile_data["working_hours"],
            profile_data["other_commitments"],
            profile_data["dating_availability"],
            profile_data["height"],
            profile_data["weight"],
            profile_data["age"],
            profile_data["gender"],
            profile_data["eye_color"],
            profile_data["eye_type"],
            profile_data["hair_color"],
            profile_data["hair_length"],
            profile_data["hair_style"],
            profile_data["nose"],
            profile_data["facial_form"],
            profile_data["cheekbones"],
            profile_data["eyebrows"],
            profile_data["dept"],
            profile_data["assets"],
            profile_data["income_this_year"],
            profile_data["income_next_year"],
            profile_data["income_over_next_year"],
            profile_data["wealth_goals"],
            profile_data["kids"],
            profile_data["pets"],
            profile_data["living"],
            profile_data["wealth_splitting"],
            profile_data["effort_splitting"],
            profile_data["religion"],
            profile_data["politics"],
            profile_data["existing_family_structure"],
            profile_data["retirement"],
            profile_data["q1"],
            profile_data["q2"],
            profile_data["q3"],
            profile_data["q4"],
            profile_data["q5"],
            profile_data["q6"],
            profile_data["q7"],
            profile_data["q8"],
            profile_data["q9"],
            profile_data["q10"],
            profile_data["unique_id"],
        ),
    )
