def update_user_profile(cursor, profile_data, bmi):
    cursor.execute(
        """
        UPDATE User_profile SET
            attractiveness = ?, relationship_type = ?, family_planning = ?, working_hours = ?, other_commitments = ?, 
            dating_availability = ?, gender = ?, height = ?, weight = ?, age = ?, city = ?, country = ?, zipcode = ?, 
            occupation = ?, languages = ?, bmi = ?, eye_color = ?, eye_type = ?, hair_color = ?, hair_length = ?, 
            hair_style = ?, nose = ?, facial_form = ?, cheekbones = ?, eyebrows = ?, body_shape = ?, sports = ?, 
            hobbies = ?, overall_health = ?, skin_helath = ?, kids = ?, pets = ?, living_space = ?, living_mates = ?, 
            wealth_splitting = ?, effort_splitting = ?, religion = ?, politics = ?, existing_family_structure = ?, 
            retirement = ?, smoking = ?, drinking = ?, drugs = ?, financial_situation = ?, dating_experince = ?, 
            taruma = ?, legal_status = ?
        WHERE unique_id = ?
        """,
        (
            profile_data["attractiveness"],
            profile_data["relationship_type"],
            profile_data["family_planning"],
            profile_data["working_hours"],
            profile_data["other_commitments"],
            profile_data["dating_availability"],
            profile_data["gender"],
            profile_data["height"],
            profile_data["weight"],
            profile_data["age"],
            profile_data["city"],
            profile_data["country"],
            profile_data["zipcode"],
            profile_data["occupation"],
            profile_data["languages"],
            bmi,
            profile_data["eye_color"],
            profile_data["eye_type"],
            profile_data["hair_color"],
            profile_data["hair_length"],
            profile_data["hair_style"],
            profile_data["nose"],
            profile_data["facial_form"],
            profile_data["cheekbones"],
            profile_data["eyebrows"],
            profile_data["body_shape"],
            profile_data["sports"],
            profile_data["hobbies"],
            profile_data["overall_health"],
            profile_data["skin_helath"],
            profile_data["kids"],
            profile_data["pets"],
            profile_data["living_space"],
            profile_data["living_mates"],
            profile_data["wealth_splitting"],
            profile_data["effort_splitting"],
            profile_data["religion"],
            profile_data["politics"],
            profile_data["existing_family_structure"],
            profile_data["retirement"],
            profile_data["smoking"],
            profile_data["drinking"],
            profile_data["drugs"],
            profile_data["financial_situation"],
            profile_data["dating_experince"],
            profile_data["taruma"],
            profile_data["legal_status"],
            profile_data["unique_id"],
        ),
    )
